name: hand_tracking
on:
  push:
    branches:
      - "*"
  workflow_dispatch:

env:
  POSTGRES_DB: hand-tracking-test
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: postgres
  POSTGRES_HOST: postgres

jobs:
  testing:
    runs-on: ubuntu-latest
    container: node:latest
    services:
      postgres:
        image: postgres
        env:
          POSTGRES_DB: ${{env.POSTGRES_DB}}
          POSTGRES_PASSWORD: ${{env.POSTGRES_PASSWORD}}
        ports:
          - 5432:5432
    steps:
      - uses: actions/checkout@v3
      - run: 
          cd express_server
          yarn install 
          yarn knex migrate:latest --env test
          yarn knex seed:run
          yarn jest
  deploy:
    if: github.ref_name == 'production'
    runs-on: ubuntu-latest
    needs: testing
    steps:
      - name: ssh to pull latest version and restart
        uses: appleboy/ssh-action@master
        with:
          script: |
            cd express_server
            git pull origin main
            yarn install
            yarn knex migrate:latest --env production
            pm2 restart express-server
          host: hand-drawing.pinkman.world
          username: ubuntu
          port: 22
          key: ${{secrets.SSH_PRIVATE_KEY}}


